// Generated by https://quicktype.io

export interface MrrPxx {
    ProvEngmntReqId:                 string;
    CapabilityInd:                   string;
    HasBeenEngaged:                  string;
    MedRecReqType:                   string;
    HomePlanId:                      string;
    MemberHostPlanId:                string;
    RoutetoHostPlanId:               string;
    SourceFirstTimeSenttoHostPlanDt: string;
    FirstTimeSenttoHostPlanDt:       string;
    LastMRRProvEngmntReqID:          string;
    SouceLastMedRecReqRcptDt:        string;
    LastMedRecReqRcptDt:             string;
    RndrngProvNm:                    string;
    LastMedRecReqServRangeDts:       LastMedRecReqServRangeDts;
    ITSSubscriberId:                 string;
    SourceMemberDOB:                 string;
    MemberDateOfBirth:               string;
    MMIId:                           string;
    MemberFullName:                  string;
    MemberGender:                    string;
    BillProvProprietaryId:           string;
    RndrngProvProprietaryId:         string;
    BillProvNPI:                     string;
    RndrngProvNPI:                   string;
    RndrngProvHostPlanId:            string;
    BillProvZipCode:                 string;
    RndrngProvZipCode:               string;
    RndrngProvTxnmyCd:               string;
    SCCFIds:                         string;
    ServRangeDts:                    ServRangeDts;
    ProvEngagementInd:               string;
    ProvCntrctingSts:                string;
    HomePlanClsrInd:                 string;
    HostPlanMedRecMatchInd:          string;
    HostPlanClsrInd:                 string;
    ErrorType:                       string;
    ErrorDescription:                string;
    RequestStatusCode:               string;
    RequestStatusDescription:        string;
    RequestType:                     string;
    RequestTypeDescription:          string;
    RecordProcessStatusCode:         string;
    RecordCompletionDate:            string;
    RecordClosedDate:                string;
    CreateDatetime:                  string;
    CreateUserIdentifier:            string;
    UpdateDatetime:                  string;
    UpdateUserIdentifier:            string;
}

export interface LastMedRecReqServRangeDts {
    SourceLastmedrecreqservbegindt: string;
    LastMedRecReqServBeginDt:       string;
    SourceLastmedrecreqservenddt:   string;
    LastMedRecReqServEndDt:         string;
}

export interface ServRangeDts {
    ServBeginDt: string;
    ServEndDt:   string;
}
